"""added file owner

Revision ID: 155e086c5568
Revises: c1e19dcbda08
Create Date: 2025-11-07 16:07:28.299555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155e086c5568'
down_revision: Union[str, Sequence[str], None] = 'c1e19dcbda08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('owner', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'files', 'users', ['owner'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'owner')
    # ### end Alembic commands ###
