"""removed job as database instance

Revision ID: accd77b8dc14
Revises: 651ac8076387
Create Date: 2025-11-08 00:12:27.243424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'accd77b8dc14'
down_revision: Union[str, Sequence[str], None] = '651ac8076387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='status'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('jobs_pkey'))
    )
    # ### end Alembic commands ###
